produtoColonial/urls.py
from django.urls import path
from . import views

app_name = 'aplicacao'

urlpatterns = [
    path('produtor/produto/', views.lista_produtor, name='produtos_lista_produtor'),
    path('produto/', views.ProdutoListView.as_view(), name='produtos_lista'),
    path('produto/ver/<int:produto_id>', views.ver, name='produto_ver'),
    path('produto/atualizar/<int:produto_id>', views.atualizar, name='produto_atualizar'),
    path('produto/excluir/<int:produto_id>', views.excluir, name='produto_excluir'),
    path('produto/criar', views.criar, name='produto_criar'),
    path('cadastro/cliente', views.cadastro, name='cadastro_cliente'),
    path('pedidos/', views.pedidos, name='pedidos'),
    path('pedidos/ver/<int:pedido_id>', views.verPedido, name='pedido_ver'),
    path('pedidos/editar/<int:pedido_id>', views.editarPedido, name='pedido_editar'),
    path('produto/detalhes/<int:produto_id>', views.ver_detalhes, name='produto_detalhes'),
]

produtosColoniais/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


from ninja import NinjaAPI
from ninja.security import django_auth_superuser
from produtoColonial.router import router

api = NinjaAPI()
api.add_router(prefix="", router=router)

urlpatterns = [
    path('', views.index, name='inicio'),
    path('', include('produtoColonial.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', api.urls),

]

#add essa parte para poder caregar as img como estou na fase de dev.
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produtoColonial/models.py
from django.db import models

# Create your models here.

produtoColonial/models/admin_token.py
from django.db import models


def regenerate_key():
    from django.utils.crypto import get_random_string
    return get_random_string(40)


class AdminToken(models.Model):
    key = models.CharField(max_length=40, help_text="Deixe em branco para gerar um novo token", unique=True, blank=True)
    user = models.ForeignKey('auth.User', models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = regenerate_key()
        return super().save(*args, **kwargs)

produtoColonial/models/base.py
from django.db import models

class BaseModel(models.Model):
    class Meta:
        abstract = True
        app_label = 'produtoColonial'

produtoColonial/models/categoria.py
from produtoColonial.models.base import BaseModel
from django.db import models

class Categoria(BaseModel):
    nome = models.CharField(max_length=50, verbose_name="Nome da Categoria", help_text="Informe o nome da categoria")

    class Meta:
        abstract = False

    def __str__(self):
        return self.nome

produtoColonial/models/cliente.py
from produtoColonial.models.base import BaseModel
from django.db import models
from django.contrib.auth.models import User
#from django.contrib.auth.models import AbstractUser, Group, Permission

class Cliente(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Selecione o user do Cliente", help_text="Selecione um usuario para o cliente.")
    #nome = models.CharField(max_length=50, verbose_name="Nome", help_text="Insira o nome do Cliente")
    #sobrenome = models.CharField(max_length=50, verbose_name="Sobrenome", help_text="Insira o sobrenome do Cliente")
    cpf = models.CharField(max_length=11, unique=True, verbose_name="CPF", help_text="Informe o CPF do Cliente (obs. só números")
    #emailCliente = models.EmailField(unique=True, verbose_name="E-mail", help_text="Informe o email do cliente")
    celular = models.CharField(max_length=11, verbose_name="Celular", help_text="Informe o celular do cliente com o DDD")
    cep = models.CharField(max_length=15, verbose_name="CEP", help_text="Informe o CEP do endereço do Cliente")
    endereco = models.CharField(max_length=150, verbose_name="Endereço", help_text="Informe a Rua, Número da casa, Bairro e Cidade")
    #groups = models.ManyToManyField(Group, related_name='cliente_set', blank=True)
    #user_permissions = models.ManyToManyField(Permission, related_name='cliente_permission_set', blank=True)

    class Meta:
        abstract = False
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

    #def __str__(self):
    #    return self.nome + " " + self.sobrenome

    def __str__(self):
        return self.user.get_full_name()

produtoColonial/models/ordem.py
from produtoColonial.models.base import BaseModel
from django.db import models
from produtoColonial.models.cliente import Cliente
from produtoColonial.models.produto import Produto

class Ordem(BaseModel):
    status_opcoes = [
        ('ops1', 'Não Tratado'),
        ('ops2', 'Em andamento'),
        ('ops3', 'Enviado'),
        ('ops4', 'Entregue'),
    ]

    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, verbose_name="Cliente", help_text="Selecione o Cliente que fez a compra")
    produtos = models.ManyToManyField(Produto, verbose_name="Selecione os produtos comprados", help_text="Neste campo você deve selecionar os produtos que o cliente compro")
    status = models.CharField(max_length=20, choices=status_opcoes, default='ops1', verbose_name="Status", help_text="Selecione o andamento da Ordem")

    class Meta:
        abstract = False

    def __str__(self):
        return self.cliente.nome + " (Status: " + self.status + " )"

produtoColonial/models/pedido.py
from produtoColonial.models.base import BaseModel
from django.db import models
from produtoColonial.models.cliente import Cliente
from produtoColonial.models.produto import Produto

class Pedido(BaseModel):
    class OpcoesStatus(models.TextChoices):
        NAO_TRATADO = ("nt", "Não Tratado")
        EM_ANDAMENTO = ("ea", "Em Andamento")
        ENVIADO = ("en", "Enviado")
        ENTREGUE = ("et", "Entregue")

    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, verbose_name="Cliente", help_text="Selecione o Cliente que fez a compra")
    produtos = models.ManyToManyField(Produto, verbose_name="Selecione os produtos comprados", help_text="Neste campo você deve selecionar os produtos que o cliente compro")
    status = models.CharField(max_length=20, choices=OpcoesStatus, default=OpcoesStatus.NAO_TRATADO, verbose_name="Status", help_text="Selecione o andamento do pedido")

    class Meta:
        abstract = False

    def __str__(self):
        return self.cliente.user.get_full_name() + " (Status: " + self.status + " )"

produtoColonial/models/plano.py
from produtoColonial.models.base import BaseModel
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Plano(BaseModel):
    nome_plano = models.CharField(max_length=50, verbose_name="Nome do Plano", help_text="Informe o nome do Plano (Exemplo: Autoatendimento ou Cesta Juntos)")
    valor = models.FloatField(verbose_name="Valor da mensalidade", help_text="Informe o valor do plano, que deve ser paga mensalmente")
    data_de_pagamento = models.IntegerField(verbose_name="Dia do Pagamento", help_text="Informe um dia para pagamento do plano (entre 01 a 31)", validators=[MinValueValidator(1), MaxValueValidator(31)])

    class Meta:
        abstract = False

    def __str__(self):
        return self.nome_plano

produtoColonial/models/produto.py
from produtoColonial.models.base import BaseModel
from django.db import models
from produtoColonial.models.produtor import Produtor
from produtoColonial.models.categoria import Categoria

class Produto(BaseModel):
    produtor = models.ForeignKey(Produtor, on_delete=models.CASCADE,verbose_name="Produtor", help_text="Selecione o produtor responsavel pelo produto")
    nome = models.CharField(max_length=50, verbose_name="Nome do Produto", help_text="Informe um nome para o produto . (ex. Mel 300g")
    imagem = models.ImageField(verbose_name="Imagem do produto", help_text="Inclua a imagem do produto")
    categoria = models.ManyToManyField(Categoria, verbose_name="Categoria", help_text="Selecione a ou as categorias que o produto pertence")
    descricao = models.TextField(max_length=800, verbose_name="Descrição do Produto", help_text="Esse campo é destinado para informações gerais e especificas do produto")
    preco = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Preço", help_text="Informe o preço do produto")

    class Meta:
        abstract = False

    def __str__(self):
        return self.nome + " - " + self.produtor.nomeFantasia

produtoColonial/forms/cliente_form.py
from django import forms
from produtoColonial.models import Cliente
from django.contrib.auth.models import User

class ClienteForm(forms.ModelForm):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    #email = forms.EmailField()
    #password = forms.CharField(widget=forms.PasswordInput())
    cpf = forms.CharField(max_length=11)
    celular = forms.CharField(max_length=11)
    cep = forms.CharField(max_length=15)
    endereco = forms.CharField(max_length=150)

    class Meta:
        model = User
        fields = ['password', 'email', 'first_name', 'last_name'] #'__all__' 'password', 'username',
        #widgets = {"user":forms.HiddenInput()} #aqui escondemos o campo User

    #Metodo save para salvar o usuário e criar uma instância de Cliente
    def save(self, commit=True):
        #Chama o mtodo save do ModelForm sem ainda commitar no banco de dados
        user = super().save(commit=False)
        # Define a senha do usuário usando set_password para garantir que seja criptografada
        user.set_password(self.cleaned_data['password'])
        user.username = self.cleaned_data['email']
        if commit:
            #Salva o objeto User no banco de dados
            user.save()
            #Cria uma instância de Cliente associada ao usuário e salva no banco de dados
            Cliente.objects.create(user=user, cpf=self.cleaned_data['cpf'], celular=self.cleaned_data['celular'], cep=self.cleaned_data['cep'], endereco=self.cleaned_data['endereco'])
        return user

produtoColonial/forms/pedido_form.py
from django import forms
from produtoColonial.models import Pedido, Produto

class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = '__all__'

produtoColonial/forms/pedido_form_status.py
from django import forms
from produtoColonial.models import Pedido, cliente


class PedidoFormStatus(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ["status"]

produtoColonial/forms/produto_form.py
from django import forms
from django.contrib.auth.models import User

from produtoColonial.models import Produto, Produtor


class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = '__all__'

        # widgets = { #Configura modelo de exibição do formulario na WEB, para cada item
        #    "title": TextInput(attrs={"class": "form-control",})
        # }

    def __init__(self, *args, **kwargs):
        user: User = kwargs.pop('user')
        super(ProdutoForm, self).__init__(*args, **kwargs)

        if user.is_staff:
            self.fields['produtor'].queryset = Produtor.objects.all()
        else:
            self.fields['produtor'].initial = Produtor.objects.get(user=user)
            self.fields['produtor'].widget = forms.HiddenInput()

produtoColonial/views.py
from django.shortcuts import render

# Create your views here.

produtoColonial/views/cadastro_cliente.py
from django.shortcuts import render, get_object_or_404, redirect
from produtoColonial.forms.cliente_form import ClienteForm
from django.contrib.auth import login

def cadastro(request):
    if request.method == 'POST':
        #print("Chegou os dados")
        #print(request.POST)
        form = ClienteForm(request.POST)
        #print(form.is_valid())
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('inicio') # Redirecionar para a página inicial ou outra página após o login
        print(form.errors)
        return render(request, 'produtoColonial/cadastro_clientes.html', {'form': form})
    else:
        form = ClienteForm()
    return render(request, 'produtoColonial/cadastro_clientes.html', {'form': form})

produtoColonial/views/pedidos.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from produtoColonial.models.pedido import Pedido
from produtoColonial.forms.pedido_form import PedidoForm
from produtoColonial.forms.pedido_form_status import PedidoFormStatus

@login_required
def pedidos(request):
    pedidos = Pedido.objects.all()
    conteudo = {
        'pedidos': pedidos
    }
    return render(request, "produtoColonial/pedidos.html", conteudo)


@login_required
def verPedido(request, pedido_id):
    pedido = get_object_or_404(Pedido, pk=pedido_id)
    conteudo = {
        "pedido": pedido,
    }
    return render(request, 'produtoColonial/pedido_ver.html', conteudo)

@login_required
def editarPedido(request, pedido_id):
    pedido = get_object_or_404(Pedido, pk=pedido_id)
    try:
        if request.method == "POST":
            form = PedidoFormStatus(request.POST, files=request.FILES, instance=pedido)
            if form.is_valid():
                form.save()
                return redirect('aplicacao:pedidos')
        else:
            form = PedidoFormStatus(instance=pedido)
        conteudo = {
            "form": form,
            "pedido_id": pedido_id,
        }
        return render(request, 'produtoColonial/pedido_edit.html', conteudo)
    except:
        return redirect(request, 'produtoColonial/pedidos.html')

produtoColonial/views/produto.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView

from produtoColonial.decorators import produtor_only
from produtoColonial.models import Categoria
from produtoColonial.models.produto import Produto
from produtoColonial.forms.produto_form import ProdutoForm
from django.contrib.auth.decorators import login_required

@login_required
def lista_produtor(request, ):
    produtos = Produto.objects.filter(produtor__user=request.user)
    conteudo = {
        "produtos": produtos
    }

    return render(request, "produtoColonial/produtos_lista_produtor.html", conteudo)
@login_required
def ver(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)
    conteudo = {
        "produto": produto
    }
    return render(request, 'produtoColonial/produto_ver.html', conteudo)

@produtor_only
def atualizar(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)
    try:
        if request.method == "POST":
            form = ProdutoForm(request.POST, files=request.FILES, instance=produto, user=request.user)
            if form.is_valid():
                form.save()
                # TODO: message
                return redirect('aplicacao:produtos_lista')
        else:
            form = ProdutoForm(instance=produto, user=request.user)
            context = {
                "form": form,
                "produto_id": produto_id
            }
            return render(request, 'produtoColonial/produto_edit.html', context)
    except:
        # TODO: message
        return redirect(request, 'produtoColonial/produtos_lista_produtor.html')

@produtor_only
def criar(request):
    if request.method == "POST":
        form = ProdutoForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            form.save()
            return redirect("aplicacao:produtos_lista_produtor")
    else:
        form = ProdutoForm(user=request.user)

    context = {
        "form": form
    }
    return render(request, "produtoColonial/produto_criar.html", context)
@produtor_only
def excluir(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)
    try:
        produto.delete()
        return redirect('aplicacao:produtos_lista_produtor')
    except:
        context = {
        }
        return render(request, "produtoColonial/produtos_lista_produtor.html", context)


class ProdutoListView(ListView):
    model = Produto
    template_name = 'produtoColonial/produtos_lista.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categoria_id = self.request.GET.get('c')
        termo_pesquisa = self.request.GET.get('q')

        context['categorias'] = Categoria.objects.all()

        produto_list = Produto.objects.all()

        if termo_pesquisa is not None:
            produto_list = produto_list.filter(nome__icontains=termo_pesquisa)

        if categoria_id is not None:
            context['categoria_selecionada'] = Categoria.objects.get(pk=categoria_id)
            produto_list = produto_list.filter(categoria=categoria_id)

        context['produto_list'] = produto_list

        return context

produtoColonial/views/ver_detalhes_produto_compara.py
from django.shortcuts import render, get_object_or_404, redirect
from produtoColonial.models.produto import Produto

def ver_detalhes(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)
    conteudo = {
        "produto": produto,
    }

    return render(request, "produtoColonial/produto_detalhes.html", conteudo)

produtoColonial/templates/produtoColonial/cadastro_clientes.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block conteudo %}

    <div class="container text-center">
        <br>
        <h1>Cadastro de Clientes</h1>
        <br>
        <form action="{% url "aplicacao:cadastro_cliente" %}" method="post" class="row g-3">
            {% csrf_token %}

            <div class="row g-2">
                <div class="col">
                    {% render_field form.first_name|add_class:"form-control" placeholder="Nome" type="text" %} <!-- Aqui criamos o campo nome e colocamos as formatações -->
                </div>
                <div class="col">
                    {% render_field form.last_name|add_class:"form-control" placeholder="Sobrenome" type="text" %}
                </div>
            </div>

            <div class="col-md-4">
                {% render_field form.cep|add_class:"form-control" placeholder="CEP" %}
            </div>

            <div class="col-md-5">
                {% render_field form.endereco|add_class:"form-control" placeholder="Endereço" %}
            </div>

            <div class="col-md-3">
                {% render_field form.celular|add_class:"form-control" placeholder="Celular" type="tel" %}
            </div>

            <div class="col-md-4">
                {% render_field form.cpf|add_class:"form-control" placeholder="CPF" %}
            </div>

            <div class="col-md-4">
                {% render_field form.email|add_class:"form-control" placeholder="E-mail" type="email" %}
            </div>

            <div class="col-md-4">
                {% render_field form.password|add_class:"form-control" placeholder="Senha" type="password" %}
            </div>

            <div style="text-align: right">
                <button type="submit" class="btn btn-success"><i class="bi bi-person-fill-add"></i> Registrar</button>
            </div>

        </form>
    <br>
    </div>

{% endblock %}

produtoColonial/templates/produtoColonial/pedido_edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block conteudo %}
     <h1>Edição do Pedido</h1>

    <form action="{% url 'aplicacao:pedido_editar' pedido_id %}" method="post">
        {% csrf_token %}
        <div class="col-12">
            <div class="col">
                <div class="input-group">
                    <span class="input-group-text">Cliente</span>
                    <p class="form-control bordered-field">{{form.instance.cliente}}</p>
                </div>
            </div>

            <div class="row input-group p-2">
                <div class="col">
                    <div class="input-group">
                        <span class="input-group-text">Produtos</span>
                        <p class="form-control bordered-field">{{ form.instance.produtos.all|join:", " }}</p>
                    </div>
                </div>
            </div>

            <div class="col-5">
                {% render_field form.status|add_class:"form-select" %}
            </div>


        </div>

        <div style="text-align: right">
            <button type="submit" class="btn btn-success">
                <i class="bi bi-floppy"></i> Salvar
            </button>

            <button type="reset" class="btn btn-danger">
                <i class="bi bi-x-circle"></i> Repor
            </button>

            <a class="btn btn-primary" href="{% url 'aplicacao:pedidos' %}" role="button">
                <span class="text-light text-center">
                    <i class="bi bi-arrow-counterclockwise"></i> Voltar
                </span>
            </a>
        </div>
    </form>

{% endblock %}

produtoColonial/templates/produtoColonial/pedido_ver.html
{% extends 'base.html' %}

{% block conteudo %}
    <br>
    <h1>Informações do Pedido</h1>
    <br>
    <table class="table">

        <thead>
            <tr>
                <th scope="col">Campo</th>
                <th scope="col">Valor</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th scope="col">Id</th>
                <td>{{ pedido.id }}</td>
            </tr>

            <tr>
                <th scope="col">Nome do Cliente</th>
                <td>{{ pedido.cliente }}</td>
            </tr>

            <tr>
                <th scope="col">Produtos</th>
                <td>{{ pedido.produtos.all|join:", " }}</td>
            </tr>

            <tr>
                <th scope="col">Status</th>
                <td>{{ pedido.get_status_display }}</td>
            </tr>
        </tbody>

    </table>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-warning" href="{% url 'aplicacao:pedido_editar' pedido.id %}" role="button">
            <span class="text-light text-center">
                <i class="bi bi-pencil-fill"></i> Editar
            </span>
        </a>
        <a class="btn btn-primary" href="{% url 'aplicacao:pedidos' %}" role="button">
            <span class="text-light text-center">
                <i class="bi bi-arrow-counterclockwise"></i> Voltar
            </span>
        </a>
    </div>

{% endblock %}

produtoColonial/templates/produtoColonial/pedidos.html
{% extends 'base.html' %}

{% block conteudo %}

        {% if pedidos %} <!-- pedidos {vem no arquivo views}-->
            <div class="container text-center">
                <div class="row">
                    <h1 class="p-3">Lista de Pedidos</h1>

                    <table class="table">
                      <thead>
                        <tr>
                            <th scope="col">Pedido</th>
                            <th scope="col">Cliente</th>
                            <th scope="col">Status</th>
                            <th scope="col">Ações</th>
                        </tr>
                      </thead>
                      <tbody>

                      {% for pedido in pedidos %}
                        <tr>
                            <td>{{ pedido.id }}</td>
                            <td>{{ pedido.cliente }}</td>
                            <td>{{ pedido.get_status_display }}</td>
                            <td>
                                <a class="btn btn-primary" href="{% url 'aplicacao:pedido_ver' pedido.id %}" role="button">
                                <span class="text-light text-center">
                                    <i class="bi bi-eye-fill"></i>
                                </span>

                                </a>

                                <a class="btn btn-warning" href="{% url 'aplicacao:pedido_editar' pedido.id %}" role="button">
                                    <span class="text-light text-center">
                                        <i class="bi bi-pencil-fill"></i>
                                    </span>
                                </a>
                            </td>
                        </tr>
                      {% endfor %}

                      </tbody>
                    </table>
            {% else %}
            <div class="container text-center">
                <div class="col">
                    <br>
                    <h2>Não foi encontrado pedidos cadastrados</h2>
                </div>
            </div>
            {% endif %}
                </div>
            </div>
{% endblock %}

produtoColonial/templates/produtoColonial/produto_criar.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block conteudo %}
    <br>
    <h1>Cadastrar Produto</h1>

    <form action="{% url 'aplicacao:produto_criar' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="container text-center p-3">
             <div class="row g-2 p-2">
                 <div class="col">
                     {% render_field form.nome|add_class:"form-control" placeholder="Nome do produto" type="text" %} <!-- Aqui criamos o campo nome e colocamos as formatações -->
                 </div>
                 <div class="col">
                     {% render_field form.imagem|add_class:"form-control" placeholder="Imagem" type="file" %}
                 </div>
             </div>

            <div class="row g-2 p-2">
                <div class="col-6">
                    <div class="input-group">
                      <span class="input-group-text">Categoria</span>
                      {% render_field form.categoria|add_class:"form-select" %}
                    </div>
                </div>

                <div class="col-6">
                    <div class="input-group">
                        <span class="input-group-text">R$:</span>
                        {% render_field form.preco|add_class:"form-control" type="number" placeholder="Preço" %}
                    </div>
                </div>
            </div>

            <div class="row input-group p-2">
                <div class="col">
                    <div class="input-group">
                      <span class="input-group-text">Descição</span>
                      {% render_field form.descricao|add_class:"form-control" placeholder="Escreva aqui a descrição do seu produto!" %}
                    </div>
                </div>
            </div>

            {% render_field form.produtor|add_class:"form-select" %}

        </div>

            <div style="text-align: right" class="p-2">
                <button type="submit" class="btn btn-success">
                    <i class="bi bi-floppy"></i> Salvar
                </button>

                <button type="reset" class="btn btn-danger">
                    <i class="bi bi-x-circle"></i> Repor
                </button>

                <a class="btn btn-primary" href="{% url 'aplicacao:produtos_lista_produtor' %}" role="button">
                    <span class="text-light text-center">
                        <i class="bi bi-arrow-counterclockwise"></i> Voltar
                    </span>
                </a>
            </div>

    </form>

{% endblock %}

produtoColonial/templates/produtoColonial/produtos_lista_produtor.html
{% extends 'base.html' %}

{% block conteudo %}

        {% if produtos %} <!-- produtos {vem no arquivo views}-->
            <div class="container text-center">
                <div class="row">
                    <h1 class="p-3">Lista de Produtos</h1>

                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <a class="btn btn-success" href="{% url 'aplicacao:produto_criar' %}" role="button">
                          <span class="text-light text-center">
                              <i class="bi bi-plus-circle"></i> Cadastrar
                          </span>
                        </a>
                    <br>
                    </div>

                    <table class="table">
                      <thead>
                        <tr>
                            <th scope="col">Produto</th>
                            <th scope="col">Categoria</th>
                            <th scope="col">Preço</th>
                            {% if user.produtor %}
                            <th scope="col">Ações</th>
                            {% endif %}
                        </tr>
                      </thead>
                      <tbody>

                      {% for produto in produtos %}
                        <tr>
                            <td>{{ produto.nome }}</td>
                            <td>{{ produto.categoria.all|join:", "  }}</td>
                            <td>{{ produto.preco }}</td>
                            {% if user.produtor %}
                            <td>
                                <a class="btn btn-primary" href="{% url 'aplicacao:produto_ver' produto.id %}" role="button">
                                <span class="text-light text-center">
                                    <i class="bi bi-eye-fill"></i>
                                </span>

                                </a>

                                <a class="btn btn-warning" href="{% url 'aplicacao:produto_atualizar' produto.id %}" role="button">
                                    <span class="text-light text-center">
                                        <i class="bi bi-pencil-fill"></i>
                                    </span>
                                </a>

                                <a class="btn btn-danger" href="{% url 'aplicacao:produto_excluir' produto.id %}" role="button">
                                    <span class="text-light text-center">
                                        <i class="bi bi-trash-fill"></i>
                                    </span>
                                </a>
                            </td>
                        {% endif %}
                        </tr>
                      {% endfor %}

                      </tbody>
                    </table>
            {% else %}
            <div class="container text-center">
                <div class="col">
                    <br>
                    <h2>Não foi encontrado produtos cadastrados</h2>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-cet">
                    <div class="d-grid gap-2 d-md-flex justify-content-md-edn">
                        <a class="btn btn-success" href="{% url 'aplicacao:produto_criar' %}" role="button">
                            <span class="text-light text-center">
                                <i class="bi bi-plus-circle"></i> Cadastrar Produto
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            {% endif %}
                </div>
            </div>
{% endblock %}